### ISSUE TITLE
`device-usage/block` not linking on ukvm

### ISSUE THREAD

**Issue by regularfry** [mirage/mirage-skeleton#245] opened 2017-10-23 06:59 UTC
I've run into this issue on `device-usage/block` (and I get the same for the other `device-usage` examples, this one is just the first I ran into): https://gist.github.com/anonymous/23631b225f36c19cd8ec54ad9add168f

It's breaking because it can't find the `caml_alloc_pages` symbol.  I'm afraid I don't know the build system well enough to be able to tell whether the `caml_alloc_pages` symbol shouldn't exist in a `ukvm` build, or whether the package providing it isn't being given to the linker.

This is building on Linux Mint 18.2, for reference.

**Comment by regularfry** [comment] 2017-10-23 07:02
If I target the `unix` backend, `device-usage/block` builds and runs fine. I don't have a Xen setup which would allow me to test that, unfortunately, and switching to `mirage configure -t virtio` complains about a package conflict that I'm not sure how to resolve:

```
  $ make depend
opam pin add --no-action --yes mirage-unikernel-block_test-virtio .
[NOTE] Package mirage-unikernel-block_test-virtio is already path-pinned to
       /home/alex/src/mirageotron/hello-world/device-usage/block.
       This will erase any previous custom definition.
Proceed ? [Y/n] y

[mirage-unikernel-block_test-virtio] /home/alex/src/mirageotron/hello-world/device-usage/block/ synchronized
[mirage-unikernel-block_test-virtio] Installing new package description from
/home/alex/src/mirageotron/hello-world/device-usage/block

opam depext --yes --update mirage-unikernel-block_test-virtio
# Detecting depexts using flags: x86_64 linux linuxmint
# No extra OS packages requirements found.
opam install --yes --deps-only mirage-unikernel-block_test-virtio

=-=- Synchronising pinned packages =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
[mirage-unikernel-block_test-virtio] /home/alex/src/mirageotron/hello-world/device-usage/block/ already up-to-date
Your request can't be satisfied:
  - solo5-kernel-ukvm.0.2.2-1 is in conflict with solo5-kernel-virtio.0.2.2-1

No solution found, exiting
Makefile:12: recipe for target 'depend' failed
make: *** [depend] Error 3

```

**Comment by hannesm** [comment] 2017-10-23 15:32
so far, only `solo5-kernel-virtio` or `solo5-kernel-ukvm` can be installed in a single opam switch.  in order to use the virtio backend, you'll need to manually `opam remove solo5-kernel-ukvm`, and then a `make depend` will install `solo5-kernel-virtio` for you.

**Comment by regularfry** [comment] 2017-10-24 11:57
Ok, but I'd *really* rather have `ukvm` working :)

**Comment by hannesm** [comment] 2017-10-24 12:30
@regularfry you can install another switch `opam create -a virtio 4.05.0`, do the ``eval `opam config env` ``, and `opam install mirage solo5-kernel-virtio` in there :)

**Comment by yomimono** [comment] 2018-01-06 15:46
I can't reproduce the original issue (inability to link when using `-t ukvm`), so I'm going to close this; please feel free to reopen if you're still having trouble. :)

**Closed by yomimono** 2018-01-06 15:46 UTC
